<a href="https://colab.research.google.com/github/kdahun/bigdata2023/blob/main/dataAnalyze2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 넘파이 어레이 저장및 불러오기

In [8]:
import numpy as np
data = np.random.randn(3,4)
print(data)

[[ 0.14169187 -0.32862183 -0.44805125 -0.59152761]
 [-1.39747538 -1.57592327 -0.27573661 -2.05637179]
 [-1.40458223 -0.69286161 -0.19022444 -1.30381791]]


In [9]:
np.save("test_data",data)

In [10]:
load_data = np.load("test_data.npy")
print(load_data)

[[ 0.14169187 -0.32862183 -0.44805125 -0.59152761]
 [-1.39747538 -1.57592327 -0.27573661 -2.05637179]
 [-1.40458223 -0.69286161 -0.19022444 -1.30381791]]


### Series : 1차원 데이터구조(넘파이 에서 벡터와 비슷)


In [16]:
import pandas as pd
from pandas import Series, DataFrame
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([1,2,3,4,5],index=list("abcde"))

In [13]:
print(s1)
print(s2)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


In [20]:
d = {"영미":80,"두현":90,"준이":70}
s3=pd.Series(d)
display(s3)

영미    80
두현    90
준이    70
dtype: int64

In [23]:
df1=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[5,6,7]])
display(df1)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
3  5  6  7

In [24]:
df3= pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],)

In [25]:
data = {"state" : ["Ohio","Ohio","Ohio","Nebada","Nebada","Nebada"],"year" : [2000,2001,2002,2001,2002,2003],
        "pop":[1.5,1.7,3.6,2.4,2.9,3.2]}
pd.DataFrame(data)

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nebada  2001  2.4
4  Nebada  2002  2.9
5  Nebada  2003  3.2

In [31]:
df = pd.DataFrame(data,columns=["year","pop","state","debt"], index = [1,2,3,4,5,6])
display(df.T)

1     2     3       4       5       6
year   2000  2001  2002    2001    2002    2003
pop     1.5   1.7   3.6     2.4     2.9     3.2
state  Ohio  Ohio  Ohio  Nebada  Nebada  Nebada
debt    NaN   NaN   NaN     NaN     NaN     NaN

In [36]:
# 열 접근하기 : 키로 인덱스 접근
df['year'] # year 열 하나 = > 시리즈


# 열 접근하기 : 속성으로 접근
display(df.state)


display(df[["pop","state"]])

1      Ohio
2      Ohio
3      Ohio
4    Nebada
5    Nebada
6    Nebada
Name: state, dtype: object

pop   state
1  1.5    Ohio
2  1.7    Ohio
3  3.6    Ohio
4  2.4  Nebada
5  2.9  Nebada
6  3.2  Nebada

In [41]:
import numpy as np
display(df['debt'])
df['debt']=np.arange(6)
df["degree"]=10
display(df)

1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
Name: debt, dtype: object

year  pop   state  debt  degree
1  2000  1.5    Ohio     0      10
2  2001  1.7    Ohio     1      10
3  2002  3.6    Ohio     2      10
4  2001  2.4  Nebada     3      10
5  2002  2.9  Nebada     4      10
6  2003  3.2  Nebada     5      10

In [42]:
# 행은 슬라이싱으로 접근

df[0:4]

year  pop   state  debt  degree
1  2000  1.5    Ohio     0      10
2  2001  1.7    Ohio     1      10
3  2002  3.6    Ohio     2      10
4  2001  2.4  Nebada     3      10

In [47]:
display(df['degree'])
display(df[4:7])

display(df[['pop','state','debt']][2:5])
display(df[2:5][['pop','state','debt']])

1    10
2    10
3    10
4    10
5    10
6    10
Name: degree, dtype: int64

year  pop   state  debt  degree
5  2002  2.9  Nebada     4      10
6  2003  3.2  Nebada     5      10

pop   state  debt
3  3.6    Ohio     2
4  2.4  Nebada     3
5  2.9  Nebada     4

pop   state  debt
3  3.6    Ohio     2
4  2.4  Nebada     3
5  2.9  Nebada     4

In [49]:
df['degree']
df.degree

1    10
2    10
3    10
4    10
5    10
6    10
Name: degree, dtype: int64

In [50]:
df.values[2:5,1:4] # 넘파이 array로 가져옴


array([[3.6, 'Ohio', 2],
       [2.4, 'Nebada', 3],
       [2.9, 'Nebada', 4]], dtype=object)

In [51]:
frame = pd.DataFrame(data,columns=["year","pop","state","debt"], index = list("abcdef"))
frame['debt']=np.arange(6)
frame["degree"]=10

display(frame)

year  pop   state  debt  degree
a  2000  1.5    Ohio     0      10
b  2001  1.7    Ohio     1      10
c  2002  3.6    Ohio     2      10
d  2001  2.4  Nebada     3      10
e  2002  2.9  Nebada     4      10
f  2003  3.2  Nebada     5      10

In [56]:
frame.iloc[:,4]
frame.iloc[4:6]

year  pop   state  debt  degree
e  2002  2.9  Nebada     4      10
f  2003  3.2  Nebada     5      10

In [58]:
frame.iloc[2:5,1:4]

pop   state  debt
c  3.6    Ohio     2
d  2.4  Nebada     3
e  2.9  Nebada     4

In [59]:
frame.loc[:,"degree"]

a    10
b    10
c    10
d    10
e    10
f    10
Name: degree, dtype: int64

In [63]:
frame.iloc[2:5,3:5]

debt  degree
c     2      10
d     3      10
e     4      10

In [64]:
frame.loc[["a","c"],"debt":"degree"]

debt  degree
a     0      10
c     2      10

In [67]:
frame['eastern']=frame.state=='Ohio'
print(frame.state=='Ohio')
display(frame)

a     True
b     True
c     True
d    False
e    False
f    False
Name: state, dtype: bool


year  pop   state  debt  degree  eastern
a  2000  1.5    Ohio     0      10     True
b  2001  1.7    Ohio     1      10     True
c  2002  3.6    Ohio     2      10     True
d  2001  2.4  Nebada     3      10    False
e  2002  2.9  Nebada     4      10    False
f  2003  3.2  Nebada     5      10    False

In [72]:
dset={"영미":{"국어" : 80,"수학":90,"음악":100},
      "두현":{"국어" : 100,"수학":98,"음악":90},
      "준이":{"국어" : 95,"수학":93,"음악":92}}
weight=np.array([1,1.2,2])
df_st = pd.DataFrame(dset).T

In [77]:
total = df_st*weight

In [80]:
total['총점']=total.sum(1)

In [84]:
total['평균']=total.loc[:,'국어':'음악'].mean(1)

In [86]:
print(total.columns)
print(total.index)
print(total.values)

Index(['국어', '수학', '음악', '총점', '평균'], dtype='object')
Index(['영미', '두현', '준이'], dtype='object')
[[ 80.         108.         200.         388.         129.33333333]
 [100.         117.6        180.         397.6        132.53333333]
 [ 95.         111.6        184.         390.6        130.2       ]]


In [87]:
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [89]:
new_obj=obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [92]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index = ['Ohio','Colorado','Utah','New York'],
                    columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [93]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [97]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [98]:
data.drop(['two','four'],axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [110]:
display(data[:2][['one','two']])
display(data[data['three']>5])

one  two
Ohio        0    1
Colorado    4    5

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [109]:
data['three']>5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [111]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [112]:
data[data<5]=0

In [113]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [116]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

In [120]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [121]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [125]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [129]:
data.iloc[[1,2],[3,0,1]]['two']

Colorado    5
Utah        9
Name: two, dtype: int64

In [130]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [134]:
data.iloc[:,:3]

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [138]:
data.three>5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [137]:
data[data['three']>5]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [131]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [139]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index = ['a','c','d','e'])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],
               index=list('acefg'))
print(s1)
print(s2)

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64
a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64


In [140]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [158]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),
                    index = ['Ohio','Texas','Colorado'],
                    columns=list('bcd'))
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),
                    index = ['Utah','Ohio','Texas','Oregon'],
                    columns=list('bde'))

display(df1)
display(df2)
display(df1.add(df2,fill_value=0))
display(df1.reindex(columns=[df2.columns,df1.columns]))

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

b   d   e
           b   c   d
Ohio     NaN NaN NaN
Texas    NaN NaN NaN
Colorado NaN NaN NaN

In [148]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                    columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                    columns=list('abcde'))
df2.loc[1,'b']=np.nan
display(df1)
display(df2)

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [149]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [150]:
df2.add(df1,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [153]:
arr= np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [154]:
arr[0]

array([0., 1., 2., 3.])

In [155]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [166]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                     columns=list('bde'),
                     index=['Utah','Ohio',"Texas","Oregon"])
series = frame.iloc[0]

In [168]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [179]:
series2 = pd.Series(range(3),index=list('bef'))
frame.add(series2,axis=1)

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [173]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [174]:
frame.sub(series3,axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [182]:
frame = pd.DataFrame(np.random.randn(4,3).reshape((4,3)),
                     columns=list('bde'),
                     index=['Utah','Ohio',"Texas","Oregon"])

frame

b         d         e
Utah   -0.368069  0.533245  0.757946
Ohio   -0.537550  0.801713  1.214576
Texas  -0.922998  0.243593 -0.823240
Oregon -0.237559 -0.217218  0.417086

In [183]:
np.abs(frame)

b         d         e
Utah    0.368069  0.533245  0.757946
Ohio    0.537550  0.801713  1.214576
Texas   0.922998  0.243593  0.823240
Oregon  0.237559  0.217218  0.417086

In [184]:
score = pd.DataFrame(dset).T
display(score)

국어  수학   음악
영미   80  90  100
두현  100  98   90
준이   95  93   92

In [185]:
english=np.array([90,95,92])
score['영어']=english

In [186]:
score

국어  수학   음악  영어
영미   80  90  100  90
두현  100  98   90  95
준이   95  93   92  92

In [187]:
score['평균']=score.mean(1)
score

국어  수학   음악  영어     평균
영미   80  90  100  90  90.00
두현  100  98   90  95  95.75
준이   95  93   92  92  93.00

In [188]:
score=score.T

In [189]:
score

영미      두현    준이
국어   80.0  100.00  95.0
수학   90.0   98.00  93.0
음악  100.0   90.00  92.0
영어   90.0   95.00  92.0
평균   90.0   95.75  93.0

In [197]:
mean = score.loc["국어":"영어",["영미","두현","준이"]].mean(1)
mean

국어    91.666667
수학    93.666667
음악    94.000000
영어    92.333333
dtype: float64

In [200]:
score2 = score.T-mean

In [201]:
score2

국어        수학        영어   음악  평균
영미      -11.666667 -3.666667 -2.333333  6.0 NaN
두현        8.333333  4.333333  2.666667 -4.0 NaN
준이        3.333333 -0.666667 -0.333333 -2.0 NaN
각 점수 평균   0.000000  0.000000  0.000000  0.0 NaN

In [206]:
score = score.T
score = score.loc["국어":"영어","영미":"준이"]

In [210]:
a = np.array([80.,100.,80.,98.])
score['은연']=a

In [232]:
score.T

국어      수학     음악     영어
영미   80.00   90.00  100.0  90.00
두현  100.00   98.00   90.0  95.00
준이   95.00   93.00   92.0  92.00
은연   80.00  100.00   80.0  98.00
평균   88.75   95.25   90.5  93.75

In [227]:
a=score.loc[:,:].mean(1)
score['평균'] = a

In [228]:
score2= score.T
score2

국어      수학     음악     영어
영미   80.00   90.00  100.0  90.00
두현  100.00   98.00   90.0  95.00
준이   95.00   93.00   92.0  92.00
은연   80.00  100.00   80.0  98.00
평균   88.75   95.25   90.5  93.75

In [229]:
score2.loc[:"은연",:].mean(1)

영미    90.00
두현    95.75
준이    93.00
은연    89.50
dtype: float64

In [233]:
# 1. english = [90,95,92] = > score 에 영어 과목 점수 넣기
# 2. "은연"  = [80,100,80,98] 추가
# 3. 각 학생의 평균 점수 구하기
# 4. 각 과목의 평균 점수 구하기
# 5.

In [244]:
score=score.T
score


국어      수학     음악     영어
영미   80.00   90.00  100.0  90.00
두현  100.00   98.00   90.0  95.00
준이   95.00   93.00   92.0  92.00
은연   80.00  100.00   80.0  98.00
평균   88.75   95.25   90.5  93.75

In [249]:
score = score.drop('평균')

In [250]:
score.loc['둘리'] = [10,20,30,40]

In [251]:
score

국어     수학     음악    영어
영미   80.0   90.0  100.0  90.0
두현  100.0   98.0   90.0  95.0
준이   95.0   93.0   92.0  92.0
은연   80.0  100.0   80.0  98.0
둘리   10.0   20.0   30.0  40.0

In [254]:
# 학생별 평균 구하기
score['평균'] = score.mean(1)
score

국어     수학     음악    영어     평균
영미   80.0   90.0  100.0  90.0  90.00
두현  100.0   98.0   90.0  95.0  95.75
준이   95.0   93.0   92.0  92.0  93.00
은연   80.0  100.0   80.0  98.0  89.50
둘리   10.0   20.0   30.0  40.0  25.00

In [260]:
# 각 과목의 평균 점수 구하기
score.mean(0)

<ipython-input-260-c4060859ef01>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  score.mean(0)


Series([], dtype: float64)

In [289]:
from sklearn import datasets

data = datasets.load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [290]:
val = data['data']
target = data['target']
target_names = data['target_names']
feature_names = data['feature_names']

In [294]:
iris_df = pd.DataFrame(val,columns=feature_names)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [296]:
iris_df['target'] = target
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [302]:
iris_df[iris_df['target']==0]['target']=target_names[0]
iris_df[iris_df['target']==1]['target']=target_names[1]
iris_df[iris_df['target']==2]['target']=target_names[2]

In [303]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        target  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [307]:
# 1. iris의 feature_names들의 평균 구하기
iris_df.loc['평균']=iris_df.iloc[:,:4].mean(0)

In [308]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0             5.100000          3.500000              1.400          0.200000   
1             4.900000          3.000000              1.400          0.200000   
2             4.700000          3.200000              1.300          0.200000   
3             4.600000          3.100000              1.500          0.200000   
4             5.000000          3.600000              1.400          0.200000   
..                 ...               ...                ...               ...   
146           6.300000          2.500000              5.000          1.900000   
147           6.500000          3.000000              5.200          2.000000   
148           6.200000          3.400000              5.400          2.300000   
149           5.900000          3.000000              5.100          1.800000   
평균            5.843333          3.057333              3.758          1.199333   

        target  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
146  virginica  
147  virginica  
148  virginica  
149  virginica  
평균         NaN  

[151 rows x 5 columns]

In [324]:
# target 정보 주가하기 + iris의 target 0번인 컬럼별 데이터 평균
print(iris_df[iris_df['target']=='setosa'].mean(1))
print(iris_df[iris_df['target']=='versicolor'].mean(1))
print(iris_df[iris_df['target']=='virginica'].mean(1))



0     2.550
1     2.375
2     2.350
3     2.350
4     2.550
5     2.850
6     2.425
7     2.525
8     2.225
9     2.400
10    2.700
11    2.500
12    2.325
13    2.125
14    2.800
15    3.000
16    2.750
17    2.575
18    2.875
19    2.675
20    2.675
21    2.675
22    2.350
23    2.650
24    2.575
25    2.450
26    2.600
27    2.600
28    2.550
29    2.425
30    2.425
31    2.675
32    2.725
33    2.825
34    2.425
35    2.400
36    2.625
37    2.500
38    2.225
39    2.550
40    2.525
41    2.100
42    2.275
43    2.675
44    2.800
45    2.375
46    2.675
47    2.350
48    2.675
49    2.475
dtype: float64
50    4.075
51    3.900
52    4.100
53    3.275
54    3.850
55    3.575
56    3.975
57    2.900
58    3.850
59    3.300
60    2.875
61    3.650
62    3.300
63    3.775
64    3.350
65    3.900
66    3.650
67    3.400
68    3.600
69    3.275
70    3.925
71    3.550
72    3.800
73    3.700
74    3.725
75    3.850
76    3.950
77    4.100
78    3.725
79    3.200
80    3.200
81    3.150
8

<ipython-input-324-0e2abab598cf>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(iris_df[iris_df['target']=='setosa'].mean(1))
<ipython-input-324-0e2abab598cf>:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(iris_df[iris_df['target']=='versicolor'].mean(1))
<ipython-input-324-0e2abab598cf>:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(iris_df[iris_df['target']=='virginica'].mean(1))


In [328]:
iris_df['평균']=iris_df.iloc[:150,:4].mean(1)


In [329]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0             5.100000          3.500000              1.400          0.200000   
1             4.900000          3.000000              1.400          0.200000   
2             4.700000          3.200000              1.300          0.200000   
3             4.600000          3.100000              1.500          0.200000   
4             5.000000          3.600000              1.400          0.200000   
..                 ...               ...                ...               ...   
146           6.300000          2.500000              5.000          1.900000   
147           6.500000          3.000000              5.200          2.000000   
148           6.200000          3.400000              5.400          2.300000   
149           5.900000          3.000000              5.100          1.800000   
평균            5.843333          3.057333              3.758          1.199333   

        target     평균  
0       setosa  2.550  
1       setosa  2.375  
2       setosa  2.350  
3       setosa  2.350  
4       setosa  2.550  
..         ...    ...  
146  virginica  3.925  
147  virginica  4.175  
148  virginica  4.325  
149  virginica  3.950  
평균         NaN    NaN  

[151 rows x 6 columns]