<a href="https://colab.research.google.com/github/kdahun/bigdata2023/blob/main/python5day.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
class Person:
  def __init__(self,name,age):
    self.name = name
    self.age = age
  def Personinfo(self):
    return self.name + ":(age:"+ str(self.age)+")"

In [6]:
my_info = Person("김다훈",23)

In [7]:
my_info.Personinfo()

'김다훈:(age:23)'

In [15]:
class Student(Person):
  def __init__(self,name,age,grade):
    Person.__init__(self,name,age)
    self.grade=grade
  def GetStudent(self):
    return self.Personinfo() + ", " + str(self.grade )

In [17]:
my_info = Student("김다훈",23,3)
my_info.GetStudent()

'김다훈:(age:23), 3'

In [18]:
my_info.Personinfo()

'김다훈:(age:23)'

In [26]:
class MyScore:
  def __init__(self,kor,eng):
    self.kor = kor
    self.eng = eng
  def getTot(self):
    return (self.kor+self.eng)

class MyScore_Sub(MyScore):
  def __init__(self,kor,eng,mat):
    self.mat = mat
    #super().__init__(kor,eng)
    MyScore.__init__(self,kor,eng)
  def getTot(self):
    #return (super().getTot()+self.mat)
    return (MyScore.getTot()+self.mat)




In [35]:
a=MyScore(57,57)
a.getTot()

114

# 메모리제이션으로 제귀함수 효율화

In [38]:
def fibo_memo(n):
  d=[0]*100
  d[1]=1
  d[2]=1

  for i in range(3,n+1):
    d[i]=d[i-1]+d[i-2]
  return d[n]

fibo_memo(5)


5

In [111]:
import requests

res = requests.get("https://media.naver.com/press/032")
print(res.status_code)
len(res.text)

200


335674

```
import requersts
from bs4 import BeautifulSoup
res = requests.get("url 넣기")
print(res.status_code)
len(res.text)

sout = BeautifulSoup(res.text,"lxml")
# 아마 가져올때 리스트로 가져오는 거 같음
soup.find("div",attrs = {"class":"class이름"})
soup.find_all("div",attrs = {"class":"class이름"})

```
.get_text()하면 text만 가져온다.

In [112]:
from bs4 import BeautifulSoup
soup=BeautifulSoup(res.text,"lxml")
print(soup.a)

<a href="#ct">본문 바로가기</a>


In [113]:
print(soup.title.get_text())




경향신문 :: 네이버뉴스



In [114]:
div=soup.find("div",attrs={"class":"press_container"})
rank1=div.find('a')
div.find_all("a")

[<a class="press_hd_prev _back_btn" href="#" onclick="nclk(event,'hom.back',032,'');">이전</a>,
 <a class="press_hd_else_button _press_list_btn" href="javascript:;" onclick="nclk(event,'hom.menu',032,'');">
 <span class="u_hc">전체 언론사 홈</span>
 </a>,
 <a class="naver-splugin spi_sns_share u_btn_sns_share" data-band-url="https://media.naver.com/press/032?lfrom=band" data-blog-blog-id="naver" data-blog-source-type="3" data-blog-url="https://media.naver.com/press/032?lfrom=blog" data-cafe-source-type="3" data-cafe-url="https://media.naver.com/press/032?lfrom=cafe" data-calendar-url="https://media.naver.com/press/032?lfrom=calendar" data-facebook-url="https://media.naver.com/press/032?lfrom=facebook" data-friend-display="on" data-friend-url="https://media.naver.com/press/032?lfrom=friend" data-kakaostory-display="off" data-kakaotalk-image-url="https://ssl.pstatic.net/static.news/image/news/m/2015/10/press_logo/032_1200x630.jpg" data-kakaotalk-url="https://media.naver.com/press/032?lfrom=kakao

In [115]:
div=soup.find("div",attrs={"class":"press_hd_ci"})

In [116]:
div.a.img

<img alt="경향신문" onerror="showNoImage(this)" src="https://imgnews.pstatic.net/image/upload/spubs/LPG0000032/logo/2022/11/24/A_145745216.png?type=u144_144"/>

In [117]:
lst=soup.find_all("li",attrs={"class":"ofra_list_item as_thumb"})

In [118]:
lst_head=[]
for i,li in enumerate(lst):
  lst_head.append(str(i+1)+"번째 뉴스"+li.find("div",attrs={"class":"ofra_list_tx_headline"}).get_text())

In [119]:
for i in lst:
  print(i.find("a",attrs={"class":"ofra_list_item_link _es_pc_link"})["href"])

https://n.news.naver.com/article/032/0003234657?ntype=RANKING
https://n.news.naver.com/article/032/0003234479?ntype=RANKING
https://n.news.naver.com/article/032/0003234580?ntype=RANKING
https://n.news.naver.com/article/032/0003234661?ntype=RANKING
https://n.news.naver.com/article/032/0003234667?ntype=RANKING
https://n.news.naver.com/article/032/0003234644?ntype=RANKING
https://n.news.naver.com/article/032/0003234664?ntype=RANKING
https://n.news.naver.com/article/032/0003234648?ntype=RANKING
https://n.news.naver.com/article/032/0003234640?ntype=RANKING
https://n.news.naver.com/article/032/0003234628?ntype=RANKING
https://n.news.naver.com/article/032/0003234667?ntype=RANKING
https://n.news.naver.com/article/032/0003234479?ntype=RANKING
https://n.news.naver.com/article/032/0003234664?ntype=RANKING
https://n.news.naver.com/article/032/0003234580?ntype=RANKING
https://n.news.naver.com/article/032/0003234649?ntype=RANKING
https://n.news.naver.com/article/032/0003234676?ntype=RANKING
https://

In [120]:
a=soup.find_all("li",attrs={"class":"press_news_item"})
for i in a:
  print(i.find("span",attrs={"class":"press_news_text"}).get_text())
  print(i.find("a",attrs={"class":"press_news_link _es_pc_link"})['href'])

“아버지 학대 당하고 있다”···배우 알랭 들롱 자녀들, 동거인 고소
https://n.news.naver.com/article/032/0003234661?type=main
[속보] 정부 “후쿠시마 오염수 방류 계획, 국제기준에 부합”
https://n.news.naver.com/article/032/0003234667?type=main
“아시아나 기내식 먹다 치아 깨져”···돌·깨진 접시조각도 나왔다
https://n.news.naver.com/article/032/0003234657?type=main
‘실종 8년만에 귀가’ 미국 남성, 알고 보니 “계속 집에 있었다”
https://n.news.naver.com/article/032/0003234644?type=main
권오수가 꺼내든 ‘김건희 녹취록’···검찰 “오히려 관계 있다는 증거”
https://n.news.naver.com/article/032/0003234580?type=main
“찍지마! XX 찍지마!” 짤로 보던 ‘그 유인촌’ 돌아왔다···과거 논란 재조명
https://n.news.naver.com/article/032/0003234479?type=main


In [24]:
import requests
from bs4 import BeautifulSoup
res1 = requests.get("https://search.daum.net/search?w=tot&q=2022%EB%85%84%EC%98%81%ED%99%94%EC%88%9C%EC%9C%84&DA=MOR&rtmaxcoll=MOR")
print(res1.status_code)
print(len(res1.text))

bSoup = BeautifulSoup(res1.text,"lxml")

200
270799


In [30]:
mov1=bSoup.find("ol",attrs={"class":"type_plural list_exact movie_list"})
mov1=mov1.find_all('li')

In [ ]:
for m in mov1:

  print(m.find("a",attrs={"class":"tit_main"}).get_text())
  print(m.find("a",attrs={"class":"tit_main"})['href'])

In [48]:
for i in range(1,6):
  img_url = mov1[i].find("img",attrs={"class":"thumb_img"})['src']
  img_res = requests.get(img_url)
  with open("rank{0}.jpg".format(i),"wb") as f:
    f.write(img_res.content)




In [42]:

res1 = requests.get("https://search.daum.net/search?w=tot&q=2022%EB%85%84%EC%98%81%ED%99%94%EC%88%9C%EC%9C%84&DA=MOR&rtmaxcoll=MOR")
print(res1.status_code)
print(len(res1.text))

bSoup = BeautifulSoup(res1.text,"lxml")
mov1=bSoup.find("ol",attrs={"class":"type_plural list_exact movie_list"})
mov1=mov1.find_all('li')

for m in mov1:

  print(m.find("a",attrs={"class":"tit_main"}).get_text())
  print(m.find("a",attrs={"class":"tit_main"})['href'])

for i in range(0,5):
  img_url = mov1[i].find("img",attrs={"class":"thumb_img"})['src']
  img_res = requests.get(img_url)
  with open("rank{0}.jpg".format(i),"wb") as f:
    f.write(img_res.content)

In [1]:
import requests
from bs4 import BeautifulSoup
for j in range(18,23):
  res = requests.get(f"https://search.daum.net/search?w=tot&q=20{j}%EB%85%84%EC%98%81%ED%99%94%EC%88%9C%EC%9C%84&DA=MOR&rtmaxcoll=MOR")
  print(res.status_code)
  print(len(res.text))

  bSoup = BeautifulSoup(res.text,"lxml")
  mov=bSoup.find("ol",attrs={"class":"type_plural list_exact movie_list"})
  mov=mov.find_all('li')

  for i in range(0,5):
    img_url = mov[i].find("img",attrs={"class":"thumb_img"})['src']
    img_res = requests.get(img_url)
    with open(f"20{j}년도 rank{i}.jpg","wb") as f:
      f.write(img_res.content)


200
281623
200
252427
200
257103
200
260106
200
270591


In [2]:
import numpy as np
list=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
arr = np.array(list)

In [9]:
print(arr.dump)
print(arr.shape)
arr[2,2:]

<built-in method dump of numpy.ndarray object at 0x7fd4c14c38d0>
(3, 4)


array([11, 12])

In [11]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [13]:
arr2 = np.arange(2,26,2).reshape(3,4)

In [14]:
arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [15]:
arr2+arr

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [27]:
from IPython.core.display import display_pretty
dset={"영미":{"국어" : 80,"수학":90,"음악":100},
      "두현":{"국어" : 100,"수학":98,"음악":90},
      "준이":{"국어" : 95,"수학":93,"음악":92}
      }

weight=[1,1.2,2.0]

lisA=[]
for i in dset.keys():
  for j in dset[i].keys():
    lisA.append(dset[i][j])



In [31]:
a=np.array(lisA).reshape(3,3)*weight

In [35]:
a[0].sum()

388.0

In [34]:
a[0].mean()

129.33333333333334

In [36]:
for i in range(3):
  print(a[i].sum())
  print(a[i].mean())

388.0
129.33333333333334
397.6
132.53333333333333
390.6
130.20000000000002
