# 와인 품질 예측

In [1]:
from sklearn.datasets import load_wine
import numpy as np
wine = load_wine()
x = wine['data']
y = wine['target']
print(np.unique(y))
print(x.shape,y.shape)

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

print(x_train,y_train)
print(x_test,y_test)

from keras.utils import to_categorical
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
print(y_train,y_test)

# z점수표준화
import numpy as np
def zscore_standize(x):
    return (x-x.mean(0))/x.std(0)

x_train = np.apply_along_axis(zscore_standize,0,x_train)
x_test = np.apply_along_axis(zscore_standize,0,x_test)

[0 1 2]
(178, 13) (178,)
[[1.181e+01 2.120e+00 2.740e+00 ... 9.500e-01 2.260e+00 6.250e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.371e+01 1.860e+00 2.360e+00 ... 1.110e+00 4.000e+00 1.035e+03]
 ...
 [1.345e+01 3.700e+00 2.600e+00 ... 8.500e-01 1.560e+00 6.950e+02]
 [1.293e+01 2.810e+00 2.700e+00 ... 7.700e-01 2.310e+00 6.000e+02]
 [1.184e+01 8.900e-01 2.580e+00 ... 7.900e-01 3.080e+00 5.200e+02]] [1 2 0 1 1 2 1 1 2 2 0 0 0 0 1 0 0 1 2 1 0 2 0 1 1 1 2 2 1 1 1 1 0 2 1 0 1
 1 1 0 2 2 1 1 0 2 0 0 1 1 0 1 1 0 2 2 0 0 2 0 0 1 0 1 2 2 1 2 0 1 2 1 1 1
 1 1 0 0 2 1 2 0 1 0 2 1 1 1 2 0 1 2 2 0 1 0 0 0 0 2 2 0 2 2 1 1 1 2 1 1 0
 1 2 2 2 0 0 1 1 1 0 2 0 1 1 1 1 1 2 1 1 1 1 2 2 1 0 1 0 2 2 1]
[[1.376000e+01 1.530000e+00 2.700000e+00 1.950000e+01 1.320000e+02
  2.950000e+00 2.740000e+00 5.000000e-01 1.350000e+00 5.400000e+00
  1.250000e+00 3.000000e+00 1.235000e+03]
 [1.225000e+01 4.720000e+00 2.540000e+00 2.100000e+01 8.900000e+01
  1.380000e+00 4.700000e-01 5.30000

Using TensorFlow backend.


In [4]:
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping
from keras.layers import Dense, Flatten, Input,Dropout

model = Sequential()

model.add(Dense(units=64,activation='relu',input_dim=13))
model.add(Dropout(0.2))
model.add(Dense(units=128,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(units=3,activation='softmax'))


early_stopping = EarlyStopping()

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
# sgd



model.fit(x_train,y_train,epochs=100,batch_size=32, validation_data=(x_test, y_test),callbacks=[early_stopping]) # 테스트에 대한 
loss_and_metrics = model.evaluate(x_train,y_train,batch_size=100) # 평가지표?

classes=model.predict(x_train,batch_size=128) # 예측한 결과 y_hat이다.

Epoch 1/100
5/5 [==============================] - 0s 37ms/step - loss: 0.9604 - accuracy: 0.5710 - val_loss: 0.7635 - val_accuracy: 0.8611
Epoch 2/100
5/5 [==============================] - 0s 9ms/step - loss: 0.7859 - accuracy: 0.7611 - val_loss: 0.6291 - val_accuracy: 0.8889
Epoch 3/100
5/5 [==============================] - 0s 8ms/step - loss: 0.5784 - accuracy: 0.8876 - val_loss: 0.5125 - val_accuracy: 0.8889
Epoch 4/100
5/5 [==============================] - 0s 8ms/step - loss: 0.4609 - accuracy: 0.9406 - val_loss: 0.4180 - val_accuracy: 0.9167
Epoch 5/100
5/5 [==============================] - 0s 8ms/step - loss: 0.3445 - accuracy: 0.8941 - val_loss: 0.3400 - val_accuracy: 0.9167
Epoch 6/100
5/5 [==============================] - 0s 8ms/step - loss: 0.2678 - accuracy: 0.9407 - val_loss: 0.2818 - val_accuracy: 0.9167
Epoch 7/100
5/5 [==============================] - 0s 8ms/step - loss: 0.1883 - accuracy: 0.9791 - val_loss: 0.2412 - val_accuracy: 0.9167
Epoch 8/100
5/5 [=========